fix StringOpsTest.scala for JDK 9 or higher
`String#getChars` throws StringIndexOutOfBoundsException instead of ArrayIndexOutOfBoundsException since JDK 9

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> "abcd".getChars(0, 4, Array('x', 'y'), -13)
java.lang.ArrayIndexOutOfBoundsException
  at java.lang.String.getChars(String.java:826)
  ... 28 elided
```

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 11).
Type in expressions for evaluation. Or try :help.

scala> "abcd".getChars(0, 4, Array('x', 'y'), -13)
java.lang.StringIndexOutOfBoundsException: offset -13, count 4, length 2
  at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
  at java.base/java.lang.String.getChars(String.java:855)
  ... 28 elided
```

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 9.0.4).
Type in expressions for evaluation. Or try :help.

scala> "abcd".getChars(0, 4, Array('x', 'y'), -13)
java.lang.StringIndexOutOfBoundsException: offset -13, count 4, length 2
  at java.base/java.lang.String.checkBoundsOffCount(String.java:3101)
  at java.base/java.lang.String.getChars(String.java:866)
  ... 28 elided
```